#pragma once

enum ePacketType
{
	CS_PT_TEST = 0,
	CS_PT_LOGIN,
	CS_PT_CHECK_ID,
	CS_PT_CREATE_ACCOUNT,
	CS_PT_CREATE_CHARACTER,
	CS_PT_DELETE_CHARACTER,
	CS_PT_IN_FIELD,
	CS_PT_DOUBLE_CHECK,
	CS_PT_CHARACTERLIST,
	CS_PT_UPDATE_CHARACTERLIST,
};